# Site settings
title: Pablo Riutort
email: pablo.riutort@gmail.com
description: "Página personal de Pablo Riutort, programador y desarrollador de software."
baseurl: ""
url: "http://localhost:4000"
username: pabloriutort
twitter: grimheader

# Build settings
markdown: kramdown
permalink: pretty
